from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    PageBreak
)
from io import BytesIO
import os
import pandas as pd
import matplotlib.pyplot as plt


# =========================================================
# ✅ PROFESSIONAL GRI PDF WITH CHARTS + INSIGHTS
# =========================================================

def build_company_pdf(company_name, df, kpis, category=None):

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # =========================================================
    # ✅ COVER PAGE
    # =========================================================

    logo_path = os.path.join("assets", "company_logo.png")
    if os.path.exists(logo_path):
        elements.append(Image(logo_path, width=160, height=90))
        elements.append(Spacer(1, 20))

    elements.append(Paragraph(f"<b>{company_name}</b>", styles["Title"]))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph("GRI Sustainability Report", styles["Title"]))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("GRI 302 — 303 — 305 — 306", styles["Normal"]))
    elements.append(Spacer(1, 50))
    elements.append(Paragraph("Generated by All-In-One GRI Platform", styles["Normal"]))
    elements.append(PageBreak())

    # =========================================================
    # ✅ KPI SUMMARY
    # =========================================================

    elements.append(Paragraph("KPI Summary", styles["Title"]))
    elements.append(Spacer(1, 20))

    if kpis:
        kpi_table_data = [["KPI Name", "Value"]]
        for k, v in kpis.items():
            kpi_table_data.append([str(k), f"{float(v):,.2f}"])

        kpi_table = Table(kpi_table_data, colWidths=[280, 150])
        kpi_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold")
        ]))

        elements.append(kpi_table)

    else:
        elements.append(Paragraph("No KPI data available.", styles["Normal"]))

    elements.append(PageBreak())

    # =========================================================
    # ✅ ALL CATEGORIES WITH CHART + INSIGHT
    # =========================================================

    if "Category" not in df.columns:
        elements.append(Paragraph("No Category column found in data.", styles["Normal"]))
    else:
        categories = sorted(df["Category"].dropna().unique().tolist())

        for cat in categories:

            cat_df = df[df["Category"] == cat]

            elements.append(Paragraph(f"GRI Category — {cat}", styles["Title"]))
            elements.append(Spacer(1, 15))

            # =====================
            # ✅ TABLE
            # =====================

            clean_df = cat_df.copy().fillna("")
            table_data = [clean_df.columns.tolist()]

            for _, row in clean_df.iterrows():
                table_data.append([str(x) for x in row.values])

            cat_table = Table(table_data, repeatRows=1)
            cat_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ]))

            elements.append(cat_table)
            elements.append(Spacer(1, 20))

            # =====================
            # ✅ CHART + INSIGHT
            # =====================

            metric_col = None
            for c in cat_df.columns:
                if "metric" in c.lower():
                    metric_col = c

            year_cols = [c for c in cat_df.columns if str(c).isdigit()]

            if metric_col and year_cols:

                row = cat_df.iloc[0]
                values = pd.to_numeric(row[year_cols], errors="coerce")

                plt.figure(figsize=(6, 3))
                plt.plot(year_cols, values, marker="o")
                plt.title(cat)
                plt.grid(True)

                chart_path = f"temp_{cat}.png"
                plt.savefig(chart_path, dpi=150, bbox_inches="tight")
                plt.close()

                if os.path.exists(chart_path):
                    elements.append(Image(chart_path, width=400, height=220))
                    elements.append(Spacer(1, 12))

                # ✅ Insight
                if len(values.dropna()) >= 2:
                    trend = values.dropna().iloc[-1] - values.dropna().iloc[0]

                    if trend > 0:
                        insight = "📈 Performance shows an increasing trend."
                    elif trend < 0:
                        insight = "✅ Performance is improving with a decreasing impact."
                    else:
                        insight = "⚠️ Performance remains stable across years."

                    elements.append(Paragraph(f"<b>Insight:</b> {insight}", styles["Normal"]))

            elements.append(PageBreak())

    # =========================================================
    # ✅ BUILD PDF
    # =========================================================

    doc.build(elements)
    buffer.seek(0)
    return buffer
