# =========================================
# ✅ FINAL PROFESSIONAL GRI PDF REPORT GENERATOR
# ✅ Colored Charts + Table of Contents + Page Numbers + Footer
# ✅ Cover Page + GRI 302 / 303 / 305 / 306 + Appendix
# =========================================

from io import BytesIO
import os

import pandas as pd
import matplotlib.pyplot as plt

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Image,
    TableOfContents
)

# --------------------------- PATHS ----------------------------
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
LOCAL_LOGO_PATH = os.path.join(ASSETS_DIR, "company_logo.png")

# --------------------------- STYLES ----------------------------
def _get_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="CenterTitle",
        parent=styles["Title"],
        alignment=TA_CENTER
    ))

    styles.add(ParagraphStyle(
        name="SectionHeader",
        parent=styles["Heading2"],
        spaceAfter=12,
        textColor=colors.HexColor("#0A3D62")
    ))

    styles.add(ParagraphStyle(
        name="NormalSmall",
        parent=styles["Normal"],
        fontSize=9
    ))

    return styles

# ---------------------- COLORED CHART GENERATOR --------------------------
def _plot_yearly_trend(yearly_df, title: str, unit: str) -> BytesIO:
    buf = BytesIO()

    years = yearly_df["Year"].astype(int)
    vals = yearly_df["total_value"]

    plt.figure(figsize=(7, 3), dpi=140)
    plt.plot(
        years, vals,
        marker="o",
        linewidth=2.5,
        color="#0A3D62"
    )
    plt.fill_between(years, vals, color="#6fa8dc", alpha=0.25)
    plt.title(title, fontsize=11)
    plt.ylabel(unit, fontsize=9)
    plt.grid(axis="y", linestyle="--", alpha=0.5)
    plt.tight_layout()
    plt.savefig(buf, format="png", bbox_inches="tight")
    plt.close()

    buf.seek(0)
    return buf

# -------------------- NUMBER FORMATTER ---------------------------
def _format_num(x):
    try:
        return f"{x:,.2f}"
    except Exception:
        return str(x)

# -------------------- FOOTER (PAGE NUMBER + COMPANY) ---------------------
def _footer(canvas, doc, company_name: str):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)

    footer_text = f"{company_name} | Page {canvas.getPageNumber()}"
    canvas.drawRightString(20 * cm, 1.2 * cm, footer_text)

    canvas.restoreState()

# ---------------------- MAIN REPORT BUILDER ------------------------------
def build_full_gri_report(company_name: str, gri_data_dict: dict) -> BytesIO:
    """
    gri_data_dict format:
    {
        "302": yearly_energy_df,
        "303": yearly_water_df,
        "305": yearly_emissions_df,
        "306": yearly_waste_df
    }

    Each yearly dataframe MUST contain:
    [Year, total_value]
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=1.7 * cm,
        bottomMargin=1.5 * cm,
        title=f"GRI Sustainability Report - {company_name}",
    )

    styles = _get_styles()
    story = []

    # ============================ COVER PAGE ================================
    if os.path.exists(LOCAL_LOGO_PATH):
        logo = Image(LOCAL_LOGO_PATH, width=6 * cm, height=6 * cm)
        logo.hAlign = "CENTER"
        story.append(Spacer(1, 2 * cm))
        story.append(logo)
    else:
        story.append(Spacer(1, 3 * cm))

    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph(f"<b>{company_name}</b>", styles["CenterTitle"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("Sustainability GRI Performance Report", styles["CenterTitle"]))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("In accordance with GRI Standards", styles["Normal"]))

    story.append(Spacer(1, 9 * cm))
    story.append(Paragraph("Generated by GRI AI Analysis Platform", styles["NormalSmall"]))
    story.append(PageBreak())

    # ============================ TABLE OF CONTENTS =========================
    story.append(Paragraph("Table of Contents", styles["SectionHeader"]))
    toc = TableOfContents()
    toc.levelStyles = [
        ParagraphStyle(fontSize=11, name='TOCHeading1', leftIndent=20, firstLineIndent=-20, spaceBefore=5),
    ]
    story.append(toc)
    story.append(PageBreak())

    # ============================ GRI SECTIONS ===============================
    gri_titles = {
        "302": "Energy Consumption (GRI 302)",
        "303": "Water Management (GRI 303)",
        "305": "Emissions (GRI 305)",
        "306": "Waste Management (GRI 306)",
    }

    for gri_code, title in gri_titles.items():

        story.append(Paragraph(title, styles["SectionHeader"]))
        story.append(Spacer(1, 0.4 * cm))

        yearly_df = gri_data_dict.get(gri_code)

        if yearly_df is None or yearly_df.empty:
            story.append(Paragraph("No data available for this GRI section.", styles["Normal"]))
            story.append(PageBreak())
            continue

        # -------- KPI SUMMARY TABLE --------
        latest = yearly_df.sort_values("Year").iloc[-1]
        latest_year = int(latest["Year"])
        latest_value = latest["total_value"]

        kpi_data = [
            ["Metric", "Value"],
            ["Latest Year", str(latest_year)],
            ["Total", _format_num(latest_value)],
        ]

        kpi_table = Table(kpi_data, colWidths=[6 * cm, 8 * cm])
        kpi_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0A3D62")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ])
        )

        story.append(kpi_table)
        story.append(Spacer(1, 0.4 * cm))

        # -------- COLORED TREND CHART --------
        chart = _plot_yearly_trend(yearly_df, title, "")
        story.append(Image(chart, width=15 * cm, height=4.5 * cm))
        story.append(Spacer(1, 0.6 * cm))

        story.append(PageBreak())

    # =============================== APPENDIX ===============================
    story.append(Paragraph("Appendix — Annual Raw Totals", styles["SectionHeader"]))

    for gri_code, title in gri_titles.items():
        yearly_df = gri_data_dict.get(gri_code)

        story.append(Paragraph(title, styles["Heading4"]))

        if yearly_df is None or yearly_df.empty:
            story.append(Paragraph("No data available.", styles["Normal"]))
            story.append(Spacer(1, 0.6 * cm))
            continue

        table_data = [["Year", "Total"]]
        for _, r in yearly_df.iterrows():
            table_data.append([
                int(r["Year"]),
                _format_num(r["total_value"])
            ])

        table = Table(table_data, colWidths=[4 * cm, 6 * cm])
        table.setStyle(
            TableStyle([
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f2f2")),
            ])
        )

        story.append(table)
        story.append(Spacer(1, 0.6 * cm))

    # =========================== BUILD DOCUMENT ============================
    doc.build(
        story,
        onFirstPage=lambda canvas, d: _footer(canvas, d, company_name),
        onLaterPages=lambda canvas, d: _footer(canvas, d, company_name),
    )

    buffer.seek(0)
    return buffer
